baseURL = "https://blog.uuuz.eu.org"
languageCode = "zh-cn"
theme = "jingzhe_2"
themesDir = "themes"
title = "北海轻歌"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
enableRobotsTXT = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[permalinks]
  posts = '/:slug/'

[params.artalk]
    server="https://c.010316.xyz/"
    site="北海轻歌"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = '唠叨'
    url = '/'
    weight = 1